const suggestionActionTypes = {
  FETCH_SUGGESTION_START: 'FETCH_SUGGESTION_START',
  FETCH_SUGGESTION_SUCCESS: 'FETCH_SUGGESTION_SUCCESS',
  FETCH_SUGGESTION_FAILURE: 'FETCH_SUGGESTION_FAILURE',
  CLEAR_SUGGESTION: 'CLEAR_SUGGESTION',
};

export default suggestionActionTypes;
